#!/bin/bash

inputfile="./input.txt"
if [ ! -f "$inputfile" ]
then
	touch input.txt
fi

if [ $# != 1 ]
then
  echo "usage: ./run word or ./run char"
  exit 1
fi

isValid=true
isWord=false
if [ "$1" == "word" ]
then
  isWord=true
elif [ "$1" == "char" ]
then
  isWord=false
else
  isValid=false
fi

if [ "$isValid" = false ]
then
  echo "usage: ./run word or ./run char"
  exit 2
fi

make clean
make
rm $inputfile
touch $inputfile
vim $inputfile

echo
echo
echo

if [ "$isWord" = true ]
then
  ./counter word
else
  ./counter char
fi
exit 0
